### ISSUE TITLE
Mislabelled solder jumpers

### ISSUE THREAD

**Issue by omerk** [adafruit/Adafruit-SCD-4x-PCB#1]
Hi,

There appears to be a mismatch between the silkscreen labels that annotate the solder jumpers and what they are actually connected to.

(I've added net names PU_PWR and SENSOR_VDD to highlight the issue)

![image](https://user-images.githubusercontent.com/9847/175405340-bee2c868-7eb7-47aa-8c2a-730f1ca4af8c.png)

![image](https://user-images.githubusercontent.com/9847/175405552-41346176-2130-4702-b36b-e6fde0c0fb07.png)

![image](https://user-images.githubusercontent.com/9847/175405631-4d13f24c-e31c-4820-a8ef-f1f65342d651.png)

So, SJ1 should really be "I2C logic" and SJ2 "Sensor Power". This is reversed in the board files in this repo and also the breakout I have in front of me.

**Comment by ladyada** [comment]
woops - fixing on the next PCB run!
@kattni can u update the guide with an alert so people are bewarned :)

**Comment by kattni** [comment]
Corrected silk has already been released in the shop. The guide has been updated to reflect the correct labels, and includes a warning about the initial run having incorrect labels. Thanks for reporting this!
